### ISSUE TITLE
Discussion of colour brightness

### ISSUE THREAD

**Issue by rowlap** [pimoroni/sn3218#13]
The white LEDs are much brighter at full power than the other colours.

- Should the library provide (by default / optionally) a way to balance brightness?
- This is more of a problem for directly viewed patterns, vs indirect illumination. (I wouldn't want my piglow capped to 50% white brightness if built into a larger system.)
- Is this library used for anything other than piglow? It's no good "fixing" OUT10 / OUT11 / OUT13 then finding they don't only connect to white piglow LEDs

For example, David Hunt's examples use a `correction` table to rebalance:
http://www.davesmotleyprojects.com/raspi/raspi-piglow-module/piglow-tutorial.py

**Comment by rowlap** [comment]
I'll try to work up calibrate.py or similar to assist in getting output levels right.

**Comment by Gadgetoid** [comment]
This is a problem across the whole - spectrum - of lighting products- getting colour balancing/intensity levels right is tricky and I'm not sure there's an accessibly objective way to do it. (in the monitor world people buy £100+ display calibrator solutions for this) Usually as simple lazy good enough gamma table works because nobody really pays much attention to the colour specitivity. But, in this case, you're right- although we've discontinued the sn3218 breakout it wont be our last add-your-own-LEDs driver board and some sort of general purpose LED calibrator project might be appreciated across the makersphere.
